### PR TITLE
Reports unicode

### PR DESCRIPTION
**Pull request by FodT**
this is a potential fix for issue #63
the csv module in python 2.7 isn't very well behaved. 
Introduce an explicit handler for python 2.7
comments welcome.

### CODE REVIEW

**Comment by FodT** [comment]
this is a potential fix for issue #63

**Comment by pswaminathan** [comment]
We're already decoding the response in the line as the get call. Let's just avoid doing anything there and then decode if it's Python 3. Or better, just make the `decode_unicode` argument a Python 2/3 variable. Better than having a separate stack frame for it.

**Comment by pswaminathan** [comment]
@FodT can you test pswaminathan/FodT-reports-unicode@42fe3ab550e36191a8dc70a72eca92ec6db59a3c and see if that works? There was a merge conflict here and I made a Python2/3 flag for decode_unicode.

**Comment by FodT** [comment]
I ran into one problem with `python setup.py test` - six 1.10.0 was brought in by mock and this does not contain 'wraps'. I think we need to pin the dependency versions in the requirements.

**Pull request merged**
