### PR TITLE
Update LICENSE and change to Apache 2

### PR DESCRIPTION
**Pull request by fsargent**

### CODE REVIEW

**Comment by pswaminathan** [comment]
The only concern here is that all contributors need to consent to re-licensing their contributions under Apache 2.0. All MediaMath contributors are auto-consenting. The only external contributor is Emmanuel Job.

@emmanueljob : are you ok with re-licensing your contributions under Apache 2.0?

**Comment by pswaminathan** [comment]
Additionally, [setup.py:43](https://github.com/MediaMath/t1-python/blob/master/setup.py#L43) lists the license as BSD. Can you change that as well?

**Comment by emmanueljob** [comment]
I am ok with the re-licensing

**Comment by pswaminathan** [comment]
Thanks @emmanueljob !

**Pull request merged**
